# Generated by Django 4.2 on 2023-05-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='category_id',
            new_name='category',
        ),
    ]
