# Generated by Django 4.2 on 2023-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_id_vacancy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default=0, max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
