# Generated by Django 4.2 on 2023-05-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='user_type',
        ),
    ]
