# Generated by Django 4.2 on 2023-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryID',
            field=models.IntegerField(default=0, verbose_name='Category ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of category'),
        ),
    ]
