# Generated by Django 4.2 on 2023-04-05 10:10

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_categoryid_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryID',
        ),
        migrations.AddField(
            model_name='product',
            name='categoryName',
            field=models.CharField(default=builtins.all, max_length=50, verbose_name='Name of category'),
            preserve_default=False,
        ),
    ]
