# Generated by Django 4.2 on 2023-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_categoryid_product_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='product',
            name='categoryID',
            field=models.IntegerField(default=0, verbose_name='Category ID'),
            preserve_default=False,
        ),
    ]
